name: Data Reuters

on:
  schedule:
    - cron: '0 6,18 * * *' # Run at 6 AM and 6 PM UTC
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer Dependencies (for GitHub Actions)
        run: sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxcomposite1 libxrandr2 libgbm1

      - name: Generate Data
        run: node api/reuters/index.js

      - name: Commit files
        run: |
          git config --local user.name "actions-user"
          git config --local user.email "actions@github.com"
          git add api/wp/wapo_graphics_feed.json
          if [[ `git status --porcelain` ]]; then
            echo "OK: Changes detected."
            git commit -m "gh-action get reuters data: $(date -u)"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/iguacel/graphics-feed.git main
          else
            echo "No changes were detected."
          fi
